# Generated by Django 5.0.6 on 2024-07-01 01:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0003_alter_producto_precio'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='fecha',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
